### ISSUE TITLE
Beta-binomial negative deviance

### ISSUE THREAD

**Issue by nehill197** [poissonconsulting/extras#38]
Beta-binomial deviance sometimes negative because saturated log-likelihood is smaller than the model log-likelihood.

```{r}
dev_beta_binom(x = 1, size = 5, prob = 0.3, theta = 0.5)
```

**Comment by sebdalgarno** [comment]
perhaps worth seeing whether the other re-parameterization method has the same issues?
```
alpha = prob * theta and beta = (1 - prob) * theta
```
that one is used in the brms package

**Comment by joethorley** [comment]
done
